### ISSUE TITLE
[SC-2] 스크랩-그리디 화면 구현

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#12]
## 📝 개요
- 스크랩 프래그먼트 화면 구현

## ✅ To-Do
- [x] 스크랩 프래그먼트 화면 구현
- [x] 위로 가기 기능 구현
- [x] 제목/날짜 순 정렬 기능 구현

## 👀 ETC
-

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
