### ISSUE TITLE
[CT-1] 카테고리의 스크랩 개수 관련 컴포넌트 코드 수정

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#13]
## 📝 개요
- 스크랩 개수 관련 컴포넌트 코드 수정

## 💊 설계
- 기존 설계는 `background`의 `width`를 수정하려했으나
이를 고정하고 숫자가 항상 `background`의 중앙에 위치하도록 변경

## ✅ To-Do
- [ ] ~~스크랩 개수에 따른 background width 수정~~
- [x] 숫자 중앙 고정

## 👀 ETC
- 

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
