### ISSUE TITLE
[CT-2] add_category_bg 리소스 제거 & 직접 생성

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#16]
## 📝 개요
- add_category_bg 리소스 제거 및 직접 생성

## ✅ To-Do
- [ ] add_category_bg 리소스 제거
- [ ] 해당 컴포넌트 직접 생성

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
