### ISSUE TITLE
[CT-98] 카테고리-추가하기 에러 화면 구현

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#20]
## 📝 개요
- 에러 기능 구현

## ✅ To-Do
- [x] 아무것도 입력하지 않을 시 & 21글자 초과 시 버튼 변경
- [x] 토스트 메세지 2가지

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
