### ISSUE TITLE
[SC-5] 스크랩 세부 화면 구현

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#23]
## 📝 개요
- 스크랩 세부 화면 구현

## ✅ To-Do
- [x] 이미지 클릭 시 링크 이동
- [x] 이미지 없는 경우 default 구현
- [x] 링크 복사 버튼 클릭 시 클립보드 복사
- [x] 뒤로가기 버튼 기능 구현
- [x] 본문내용이 없는 경우 default 구현
- [x] 메모가 긴 경우 스크롤 기능

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
