### ISSUE TITLE
CT-1 카테고리

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#3]
## 📝 개요
- 카테고리 화면 구현

## ✅ To-Do
- [x]  컴포넌트들이 제 위치에 있습니다.
- [x]  버튼 클릭시 요구된 화면으로 전환됩니다.

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
