### ISSUE TITLE
[SC-6] 스크랩 세부-삭제

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#32]
## 📝 개요
- 스크랩 세부-삭제 화면 구현

## ✅ To-Do
- [x]  컴포넌트들이 제위치에 있습니다.
- [x]  버튼 클릭시 정해진 화면으로 이동합니다.
    - [x]  취소 버튼
    - [x]  삭제하기 버튼

## 👀 ETC
- custom dialog 사용

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 목요일 23:59 까지 해당 이슈에 대한 PR을 올렸어요
