### ISSUE TITLE
[SC-7] 스크랩 세부-메모 수정

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#33]
## 📝 개요
- 스크랩 세부-메모 수정

## ✅ To-Do
- [x]  컴포넌트들이 제위치에 있습니다.
- [x]  버튼 클릭시 정해진 화면으로 이동합니다.
    - [x]  취소 버튼
    - [x]  수정하기 버튼
    - [x]  < 버튼
- [x]  메모를 수정할 수 있습니다.

## 👀 ETC
- 버튼의 경우 피그마에서 그대로 코드 복사했습니다. 어떤가요? (그냥 코드로 구현하기는 어떤 방식으로 해야될 지 모르겠어요!)
- 메모 수정칸의 경우 shadow가 4dp 있어서 적용했는데 방향 커스텀이 불가능하고 색이 진한데 어떤가요? 

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 목요일 23:59 까지 해당 이슈에 대한 PR을 올렸어요
