### ISSUE TITLE
[SC-10] 스크랩 세부-즐겨찾기

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#34]
## 📝 개요
- 스크랩 세부-즐겨찾기

## ✅ To-Do
- [x]  컴포넌트들이 제위치에 있습니다.
- [x]  즐겨찾기 버튼 클릭시 토글할 수 있습니다.

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 목요일 23:59 까지 해당 이슈에 대한 PR을 올렸어요
