### ISSUE TITLE
[SC-7] 그림자 관련

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#38]
## 📝 개요
- 그림자 관련 수정

## ✅ To-Do
- [ ] 그림자 색상 변경
- [ ] 그림자 방향 변경

## 👀 ETC
- 목요일 페어코딩 시간에 수정

## 📌 체크리스트
- [ ] 담당자를 할당했어요
- [ ] 적절한 label을 달았아요
