### ISSUE TITLE
[SC-3] 스크랩-추가하기

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#39]
## 📝 개요
- 자세한 개요 작성

## ✅ To-Do
- [x]  컴포넌트들이 제위치에 있습니다.
- [x]  버튼 클릭시 정해진 화면으로 이동합니다.
    - [x]  >버튼
    - [x]  취소 버튼
    - [x]  추가하기 버튼
- [x]  메모가 길이질 시 스크롤 됩니다.

## 👀 ETC
- 그림자 없이 구현

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [ ] 목요일 23:59 까지 해당 이슈에 대한 PR을 올렸어요
