### ISSUE TITLE
[SC-98][SC-94]  스크랩-카테고리명 수정, 스크랩-카테고리명 수정 에러

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#41]
## 📝 개요
- 자세한 개요 작성

## ✅ To-Do
- [ ]  컴포넌트들이 제위치에 있습니다.
- [ ]  버튼 클릭시 정해진 화면으로 이동합니다.
    - [ ]  완료 버튼
- [ ]  1글자도 적지 않을시 or 21자를 초과시
    - [ ]  toast 메시지를 띄웁니다.
    - [ ]  완료 버튼을 클릭할 수 없습니다.

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [ ] 담당자를 할당했어요
- [ ] 적절한 label을 달았아요
- [ ] 목요일 23:59 까지 해당 이슈에 대한 PR을 올렸어요
