### ISSUE TITLE
[SC-1] 스크랩-리스트

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#46]
## 📝 개요
-

## ✅ To-Do
- [x]  컴포넌트들이 제위치에 있습니다.
- [x]  버튼 클릭시 정해진 화면으로 이동합니다.
    - [x]  이미지 클릭 시 해당 스크랩 링크로 이동
    - [x]  스크랩 제목 or > 버튼 클릭시 → 스크랩 세부 화면으로 이동
    - [x]  리스트 버튼 클릭 → 그리드 나열로 전환
    
## 👀 ETC
- 스크랩 클릭 시 세부로 넘어가게끔 구현하는 게 어떨 지
- 제목과 링크 사이 간격은 가변이 아니라 고정으로 구현해도 될까요?
- 검색 기능은 추후 구현?
- 이미지 centerCrop?
- 가변 이미지 크기
- 그림자는?

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 목요일 23:59 까지 해당 이슈에 대한 PR을 올렸어요
