### ISSUE TITLE
[디자인] 톱바, 바텀네비게이션바 디자인 변경 및 버튼 피드백 반응 추가

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#53]
## 📝 개요
- 톱바 내 컴포넌트 위치 및 아이콘 크기 수정
- 바텀 네비게이션 바 크기 수정
- 버튼 피드백 반응 추가

## ✅ To-Do
- [ ] 톱바 내 컴포넌트 위치 및 아이콘 크기 수정
- [ ] 바텀 네비게이션 바 크기 수정
- [ ] 버튼 피드백 반응 추가

## 👀 ETC
- 미리보기가 존재하는 이미지는 ripple 효과 적용 이슈가 있어요

## 📌 체크리스트
- [ ] 담당자를 할당했어요
- [ ] 적절한 label을 달았아요
