### ISSUE TITLE
[SC-2] 스크랩-그리드 화면 내 간격 조절

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#54]
## 📝 개요
- 그리드 화면 내 간격 조절

## ✅ To-Do
- [x] 그리드 중앙 정렬
- [ ] dpi 강제 고정 ?

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
