### ISSUE TITLE
[SC-93] 스크랩-추가하기-에러

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#60]
## 📝 개요
- 스크랩-추가하기-에러

## ✅ To-Do
- [x] 링크 미입력 시 에러 토스트 메세지 출력

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [x] 목요일 23:59 까지 해당 이슈에 대한 PR을 올렸어요
