### ISSUE TITLE
[SC-99] 스크랩-리스트-정렬방법

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#61]
## 📝 개요
- 스크랩-리스트-정렬방법

## ✅ To-Do
- [x]  앱을 껐다 켜도 정렬 방법이 유지됩니다.
    - [ ]  오름차순 내림차순
    - [ ]  제목순, 스크랩한 순
    
## 👀 ETC
- spinner 사용 불가
- TextView와 LinearLayout 사용

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [ ] 목요일 23:59 까지 해당 이슈에 대한 PR을 올렸어요
