### ISSUE TITLE
스크랩 고유 색상 추가, 폰트 색상 및 배경색 설정

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#7]
## 📝 개요
- 스크랩 고유 색상 추가 작업 
- 폰트 색상 일괄 변경
- 페이지 배경색 설정

## ✅ To-Do
- [x] 스크랩 고유 색상 추가
- [x] 폰트 색상 일괄 변경
- [x] 페이지 배경색 설정

## 👀 ETC
- 

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
