### ISSUE TITLE
[SR-1] 검색

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#70]
## 📝 개요
- 검색 화면 구현

## ✅ To-Do
- [ ] 투두 내용 작성

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [ ] 담당자를 할당했어요
- [ ] 적절한 label을 달았아요
- [ ] 목요일 23:59 까지 해당 이슈에 대한 PR을 올렸어요
