### ISSUE TITLE
[SR-98] 검색-검색범위-에러

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#77]
## 📝 개요
- 자세한 개요 작성

## ✅ To-Do
- [ ] 투두 내용 작성

## 👀 ETC
- 참고자료 등 기타 내용 작성

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
- [ ] 목요일 23:59 까지 해당 이슈에 대한 PR을 올렸어요
