### ISSUE TITLE
AVD 변경을 통한 자잘한 컴포넌트 위치 수정, 적절한 주석 추가 및 @string.xml에 string 정리

### ISSUE THREAD

**Issue by HyunjeLee** [HyunjeLee/Scrap-2024#8]
## 📝 개요
- 컴포넌트 위치 수정
- 적절한 주석 추가
- string.xml에 string 정리

## ✅ To-Do
- [x] 컴포넌트 위치 수정
- [x] 적절한 주석 추가
- [x] string.xml에 string 정리

## 👀 ETC
- 

## 📌 체크리스트
- [x] 담당자를 할당했어요
- [x] 적절한 label을 달았아요
